/**:
  ros__parameters:
    video_device: "/dev/video0"
    framerate: 5.0
    io_method: "mmap"
    pixel_format: "mjpeg2rgb"
    image_width: 320
    image_height: 240
    camera_name: "webcam"
    camera_info_url: "package://usb_cam/config/webcam_info_checker.yaml"
    # brightness: 50
    # contrast: 128
    # saturation: 128
    # auto_white_balance: true
    # gain: 175
    # power_line_frequency: 60
    # auto_exposure: true
    # exposure: 666
    # backlight_compensation: true
    # sharpness: 128